apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  serviceName: my-headless
  replicas: 4
  selector:
    matchLabels:
      app: my-ss
  template:
    metadata:
      labels:
        app: my-ss
    spec:
      containers:
      - name: nginx-count
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-headless
spec:
  selector:
    app: my-ss
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
